name: tru_dating
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.19.1'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  dio: ^4.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  sizer: ^2.0.15
  confetti: ^0.7.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Cinzel
      fonts: 
        - asset: assets/fonts/CinzelBlack.ttf
          weight: 900
        - asset: assets/fonts/CinzelBold.ttf
          weight: 700
